import {Status, Task} from "../types";

export const statuses: Status[] = [
  'PLAN',
  'IN PROGRESS',
  'TESTING',
  'DONE',
];

export const taskList: Task[] = [
  {
    id: 'TSK-1111',
    title: 'Cool task 1',
    name: 'Ivan',
    surname: 'Petrov',
    status: 'PLAN',
    priority: 'MUST',
    date: '13.01.2022',
  },
  {
    id: 'TSK-1112',
    title: 'Cool task 2',
    name: 'Ivan',
    surname: 'Petrov',
    status: 'PLAN',
    priority: 'SHOULD',
    date: '12.01.2022',
  },
  {
    id: 'TSK-1113',
    title: 'Cool task 3',
    name: 'Ivan',
    surname: 'Petrov',
    status: 'PLAN',
    priority: 'COULD',
    date: '11.01.2022',
  },
  {
    id: 'TSK-1114',
    title: 'Cool task 4',
    name: 'Ivan',
    surname: 'Petrov',
    status: 'PLAN',
    priority: 'MUST',
    date: '10.01.2022',
  },
  {
    id: 'TSK-1115',
    title: 'Cool task 5',
    name: 'Ivan',
    surname: 'Petrov',
    status: 'PLAN',
    priority: 'COULD',
    date: '10.01.2022',
  },
  {
    id: 'TSK-1116',
    title: 'Cool task 6',
    name: 'Ivan',
    surname: 'Petrov',
    status: 'PLAN',
    priority: 'SHOULD',
    date: '09.01.2022',
  },
  {
    id: 'TSK-2221',
    title: 'Cool task 21',
    name: 'Petr',
    surname: 'Ivanov',
    status: 'PLAN',
    priority: 'MUST',
    date: '08.01.2022',
  },
  {
    id: 'TSK-2222',
    title: 'Cool task 22',
    name: 'Petr',
    surname: 'Ivanov',
    status: 'PLAN',
    priority: 'SHOULD',
    date: '07.01.2022',
  },
  {
    id: 'TSK-2223',
    title: 'Cool task 23',
    name: 'Petr',
    surname: 'Ivanov',
    status: 'PLAN',
    priority: 'COULD',
    date: '06.01.2022',
  },
  {
    id: 'TSK-2224',
    title: 'Cool task 24',
    name: 'Petr',
    surname: 'Ivanov',
    status: 'PLAN',
    priority: 'MUST',
    date: '05.01.2022',
  },
  {
    id: 'TSK-2225',
    title: 'Cool task 25',
    name: 'Petr',
    surname: 'Ivanov',
    status: 'PLAN',
    priority: 'SHOULD',
    date: '04.01.2022',
  },
  {
    id: 'TSK-2226',
    title: 'Cool task 26',
    name: 'Petr',
    surname: 'Ivanov',
    status: 'PLAN',
    priority: 'COULD',
    date: '03.01.2022',
  },
];
